// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const databaseUrl =
  process.env.POSTGRES_PRISMA_URL ?? process.env.DATABASE_URL ?? undefined;
const directUrl =
  process.env.POSTGRES_URL_NON_POOLING ??
  process.env.DIRECT_DATABASE_URL ??
  databaseUrl;

if (!databaseUrl) {
  throw new Error(
    "DATABASE_URL or POSTGRES_PRISMA_URL must be defined for Prisma to run."
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});

